# Generated by Django 2.2.6 on 2019-10-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
