# Generated by Django 2.2.6 on 2019-11-26 09:15

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
    ]
