# Generated by Django 2.2.6 on 2019-11-26 11:06

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191126_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
