# Generated by Django 2.2.6 on 2019-11-13 07:35

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191026_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
