# Generated by Django 2.2.6 on 2019-10-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authentication', '0003_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
