# Generated by Django 2.2.6 on 2019-11-13 07:36

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20191113_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='last name'),
        ),
    ]
