# Generated by Django 2.2.6 on 2019-11-13 07:48

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20191113_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identifier',
            field=encrypted_model_fields.fields.EncryptedCharField(default=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(),
        ),
    ]
