# Generated by Django 2.2.6 on 2019-11-13 07:49

from django.db import migrations
import django.utils.timezone
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20191113_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='identifier',
        ),
        migrations.AddField(
            model_name='customuser',
            name='USERNAME_FIELD',
            field=encrypted_model_fields.fields.EncryptedCharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
