# Generated by Django 2.2.6 on 2019-11-13 07:53

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20191113_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='USERNAME_FIELD',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=encrypted_model_fields.fields.EncryptedCharField(default=12, unique=True),
            preserve_default=False,
        ),
    ]
