# Generated by Django 2.2.6 on 2019-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
