# Generated by Django 2.2.8 on 2019-12-07 08:28

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField()),
                ('document', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=authentication.models.EncryptedCharField(max_length=150),
        ),
    ]
