# Generated by Django 2.2.8 on 2019-12-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191207_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
