# Generated by Django 2.2.6 on 2019-11-20 09:33

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20191117_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
